server {
    listen 80;
    server_name theawlacompany.com www.theawlacompany.com;

    location ~* /(?:\.env|\.git|\.aws|vendor|cgi-bin|wp-|phpinfo|debug|info|test|\.docker|\.npmrc) {
        return 404;
    }

    location ~ /\.(?!well-known) {
        return 404;
    }

    location = /backend {
        return 301 /backend/;
    }

    location /backend/ {
        rewrite ^/backend/(.*)$ /$1 break;
        proxy_pass http://tac-web-backend:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://tac-web-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name api.theawlacompany.com;

    location ~* /(?:\.env|\.git|\.aws|vendor|cgi-bin|wp-|phpinfo|debug|info|test) {
        return 404;
    }

    location / {
        proxy_pass http://tac-web-backend:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}